apiVersion: route.openshift.io/v1
kind: Route
metadata:
  creationTimestamp: null
  labels:
    app.kubernetes.io/created-by: application-service
    app.kubernetes.io/instance: code-with-quarkus-hola-iefs
    app.kubernetes.io/managed-by: kustomize
    app.kubernetes.io/name: code-with-quarkus-hola-iefs
    app.kubernetes.io/part-of: maven-redhat-com
  name: code-with-quarkus-hola-iefs
  namespace: burrzinga-tenant
spec:
  path: /
  port:
    targetPort: 8081
  to:
    kind: Service
    name: code-with-quarkus-hola-iefs
    weight: null
status: {}
