apiVersion: v1
kind: Service
metadata:
  creationTimestamp: null
  labels:
    app.kubernetes.io/created-by: application-service
    app.kubernetes.io/instance: code-with-quarkus-hola-iefs
    app.kubernetes.io/managed-by: kustomize
    app.kubernetes.io/name: code-with-quarkus-hola-iefs
    app.kubernetes.io/part-of: maven-redhat-com
  name: code-with-quarkus-hola-iefs
  namespace: burrzinga-tenant
spec:
  ports:
  - port: 8081
    targetPort: 8081
  selector:
    app.kubernetes.io/instance: code-with-quarkus-hola-iefs
status:
  loadBalancer: {}
